#!/bin/sh

# This is more portable than `which' but comes with
# the caveat of not(?) properly working on busybox's ash:
existence()
{
    type "$1" >/dev/null 2>&1
}

if ! existence go; then
  echo "GNS Registrar requires Go to build!"
  exit 1
fi

go mod tidy

