name: Linux Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install tools
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install git

      - name: Download framework
        run: |
          git clone https://github.com/TheJackiMonster/gnunet.git

      - name: Install dependencies (framework)
        run: |
          sudo apt-get -qq install meson ninja-build gcc gettext recutils uncrustify yapf3
          sudo apt-get -qq install python3-sphinx python3-sphinx-multiversion python3-sphinx-rtd-theme
          sudo apt-get -qq install libgcrypt20-dev libjansson-dev libsodium-dev libcurl4-gnutls-dev libidn2-dev libunistring-dev libsqlite3-dev libmicrohttpd-dev libltdl-dev

      - name: Build framework
        run: |
          cd gnunet
          ./bootstrap
          meson setup --prefix=/usr --libdir=lib build
          meson compile -C build
          sudo meson install -C build
          cd ..

      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: Install dependencies (library)
        run: |
          sudo apt-get -qq install ninja-build meson gcc

      - name: Build library
        run: |
          meson setup --prefix=/usr --libdir=lib build
          meson compile -C build

      - name: Install dependencies (testing)
        run: |
          sudo apt-get -qq install check

      - name: Rebuild library
        run: |
          meson setup --reconfigure --prefix=/usr --libdir=lib build
          meson compile -C build

      - name: Test library
        run: |
          meson test -C build

      - name: Install library
        run: |
          sudo meson install -C build
