#!/bin/bash
# config script for ascension-bind
#
# see: dh_installdeb(1)

# If there is no frontend, set interactive
DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-noninteractive}

# load debconf library
. /usr/share/debconf/confmodule

set -e

zonelist=$(grep "^zone" < /etc/bind/named.conf.local | grep -vE "(arpa|localhost|\"\.\")" | cut -d '"' -f2)
zonelist=$(echo -n "$zonelist" | tr '\n' ',' | sed 's/,/, /g')
trimmed=$(echo "$zonelist" | tr -d '\n')
if [ "$trimmed" = "" ]; then
    echo "There are no zones to migrate"
    exit 0
fi

# set default and ask user which zones to migrate
db_set ascension-bind/zones $zonelist
db_subst ascension-bind/zones defaults $zonelist
db_subst ascension-bind/zones zonelist $zonelist
db_input medium ascension-bind/zones || true
db_go || true

exit 0

