stages:
  - build

build:
  stage: build
  image: fedora:latest
  before_script:
    - dnf install -y rpm-build rpmdevtools dnf-plugins-core
  script:
    - rpmdev-setuptree
    - cp ./rpmbuild/SPECS/gnunet-fedora.spec ~/rpmbuild/SPECS/gnunet.spec
    - rpmbuild -bs ~/rpmbuild/SPECS/gnunet.spec
    - dnf builddep ~/rpmbuild/SRPMS/gnunet-$(cat ~/rpmbuild/SPECS/gnunet.spec | grep Version |  awk '{ print $2 }')~$(rpm --eval %{?dist}).src.rpm
    - rpmbuild --rebuild ~/rpmbuild/SRPMS/gnunet-$(cat ~/rpmbuild/SPECS/gnunet.spec | grep Version |  awk '{ print $2 }')~$(rpm --eval %{?dist}).src.rpm
    - dnf install -y ~/rpmbuild/SRPMS/gnunet-$(cat ~/rpmbuild/SPECS/gnunet.spec | grep Version |  awk '{ print $2 }')~$(rpm --eval %{?dist}).src.rpm

