# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}
%global crate quiche

Name:           rust-quiche
Version:        0.17.2
Release:        %autorelease
Summary:        🥧 Savoury implementation of the QUIC transport protocol and HTTP/3

License:        BSD-2-Clause
URL:            https://crates.io/crates/quiche
Source0:         %{crates_source}
Source1:        https://git.gnunet.org/gnunet-rpm.git/plain/rpmbuild/SOURCES/quiche-fix-metadata-auto.diff
# Automatically generated patch to strip foreign dependencies
Patch:          quiche-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
🥧 Savoury implementation of the QUIC transport protocol and HTTP/3.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license COPYING
%license deps/boringssl/LICENSE
%doc README.md

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/deps/boringssl/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+boring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+boring-devel %{_description}

This package contains library source intended for building other packages which
use the "boring" feature of the "%{crate}" crate.

%files       -n %{name}+boring-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+boringssl-boring-crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+boringssl-boring-crate-devel %{_description}

This package contains library source intended for building other packages which
use the "boringssl-boring-crate" feature of the "%{crate}" crate.

%files       -n %{name}+boringssl-boring-crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+boringssl-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+boringssl-vendored-devel %{_description}

This package contains library source intended for building other packages which
use the "boringssl-vendored" feature of the "%{crate}" crate.

%files       -n %{name}+boringssl-vendored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ffi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ffi-devel %{_description}

This package contains library source intended for building other packages which
use the "ffi" feature of the "%{crate}" crate.

%files       -n %{name}+ffi-devel
%ghost %{crate_instdir}/Cargo.toml
%{_includedir}/quiche.h
%{_libdir}/libquiche.so

%package     -n %{name}+foreign-types-shared-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+foreign-types-shared-devel %{_description}

This package contains library source intended for building other packages which
use the "foreign-types-shared" feature of the "%{crate}" crate.

%files       -n %{name}+foreign-types-shared-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fuzzing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fuzzing-devel %{_description}

This package contains library source intended for building other packages which
use the "fuzzing" feature of the "%{crate}" crate.

%files       -n %{name}+fuzzing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pkg-config-meta-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkg-config-meta-devel %{_description}

This package contains library source intended for building other packages which
use the "pkg-config-meta" feature of the "%{crate}" crate.

%files       -n %{name}+pkg-config-meta-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+qlog-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+qlog-devel %{_description}

This package contains library source intended for building other packages which
use the "qlog" feature of the "%{crate}" crate.

%files       -n %{name}+qlog-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sfv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sfv-devel %{_description}

This package contains library source intended for building other packages which
use the "sfv" feature of the "%{crate}" crate.

%files       -n %{name}+sfv-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build -f ffi

%install
%cargo_install
install -Dpm0644 -t %{buildroot}%{_libdir}/ target/release/libquiche.so
install -Dpm0644 -t %{buildroot}%{_includedir}/ include/quiche.h
# FIXME: install shared library

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
